include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = AssetCompiler

AssetCompiler_OBJC_FILES = main.m EJCAsset.m EJCImageAsset.m EJCColorAsset.m EJCAssetCatalog.m EJCAssetGroup.m

AssetCompiler_NEEDS_GUI = yes

include $(GNUSTEP_MAKEFILES)/tool.make
