include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = EJCAsset

EJCAsset_HEADER_FILES = NSBundle+EJCAsset.h NSColor+EJCAsset.h libEJCAsset.h
EJCAsset_OBJC_FILES = NSBundle+EJCAsset.m NSColor+EJCAsset.m

EJCAsset_NEEDS_GUI = yes

include $(GNUSTEP_MAKEFILES)/library.make
